# Maximum number of tabs to open
MAX_TABS = 30

# Default amount of seconds to wait in between opening tabs
PER_TAB_PAUSE = 10

# Default amount of seconds to wait for things to be settled down
SETTLE_WAIT_TIME = 30

# Amount of times to run through the test suite
ITERATIONS = 5

# Talos TP5
TEST_SITES_TEMPLATES = [
    "http://localhost:{}/tp5/thesartorialist.blogspot.com/thesartorialist.blogspot.com/index.html",
    "http://localhost:{}/tp5/cakewrecks.blogspot.com/cakewrecks.blogspot.com/index.html",
    "http://localhost:{}/tp5/baidu.com/www.baidu.com/s@wd=mozilla.html",
    "http://localhost:{}/tp5/en.wikipedia.org/en.wikipedia.org/wiki/Rorschach_test.html",
    "http://localhost:{}/tp5/twitter.com/twitter.com/ICHCheezburger.html",
    "http://localhost:{}/tp5/msn.com/www.msn.com/index.html",
    "http://localhost:{}/tp5/yahoo.co.jp/www.yahoo.co.jp/index.html",
    "http://localhost:{}/tp5/amazon.com/www.amazon.com/Kindle-Wireless-Reader-Wifi-Graphite/dp/B002Y27P3M/507846.html",
    "http://localhost:{}/tp5/linkedin.com/www.linkedin.com/in/christopherblizzard@goback=.nppvan_%252Flemuelf.html",
    "http://localhost:{}/tp5/bing.com/www.bing.com/search@q=mozilla&go=&form=QBLH&qs=n&sk=&sc=8-0.html",
    "http://localhost:{}/tp5/icanhascheezburger.com/icanhascheezburger.com/index.html",
    "http://localhost:{}/tp5/yandex.ru/yandex.ru/yandsearch@text=mozilla&lr=21215.html",
    "http://localhost:{}/tp5/cgi.ebay.com/cgi.ebay.com/ALL-NEW-KINDLE-3-eBOOK-WIRELESS-READING-DEVICE-W-WIFI-/130496077314@pt=LH_DefaultDomain_0&hash=item1e622c1e02.html",
    "http://localhost:{}/tp5/163.com/www.163.com/index.html",
    "http://localhost:{}/tp5/mail.ru/mail.ru/index.html",
    "http://localhost:{}/tp5/bbc.co.uk/www.bbc.co.uk/news/index.html",
    "http://localhost:{}/tp5/store.apple.com/store.apple.com/us@mco=Nzc1MjMwNA.html",
    "http://localhost:{}/tp5/imdb.com/www.imdb.com/title/tt1099212/index.html",
    "http://localhost:{}/tp5/mozilla.com/www.mozilla.com/en-US/firefox/all-older.html",
    "http://localhost:{}/tp5/ask.com/www.ask.com/web@q=What%27s+the+difference+between+brown+and+white+eggs%253F&gc=1&qsrc=3045&o=0&l=dir.html",
    "http://localhost:{}/tp5/cnn.com/www.cnn.com/index.html",
    "http://localhost:{}/tp5/sohu.com/www.sohu.com/index.html",
    "http://localhost:{}/tp5/vkontakte.ru/vkontakte.ru/help.php@page=about.html",
    "http://localhost:{}/tp5/youku.com/www.youku.com/index.html",
    "http://localhost:{}/tp5/myparentswereawesome.tumblr.com/myparentswereawesome.tumblr.com/index.html",
    "http://localhost:{}/tp5/ifeng.com/ifeng.com/index.html",
    "http://localhost:{}/tp5/ameblo.jp/ameblo.jp/index.html",
    "http://localhost:{}/tp5/tudou.com/www.tudou.com/index.html",
    "http://localhost:{}/tp5/chemistry.about.com/chemistry.about.com/index.html",
    "http://localhost:{}/tp5/beatonna.livejournal.com/beatonna.livejournal.com/index.html",
    "http://localhost:{}/tp5/hao123.com/hao123.com/index.html",
    "http://localhost:{}/tp5/rakuten.co.jp/www.rakuten.co.jp/index.html",
    "http://localhost:{}/tp5/alibaba.com/www.alibaba.com/product-tp/101509462/World_s_Cheapest_Laptop.html",
    "http://localhost:{}/tp5/uol.com.br/www.uol.com.br/index.html",
    "http://localhost:{}/tp5/cnet.com/www.cnet.com/index.html",
    "http://localhost:{}/tp5/ehow.com/www.ehow.com/how_4575878_prevent-fire-home.html",
    "http://localhost:{}/tp5/thepiratebay.org/thepiratebay.org/top/201.html",
    "http://localhost:{}/tp5/page.renren.com/page.renren.com/index.html",
    "http://localhost:{}/tp5/chinaz.com/chinaz.com/index.html",
    "http://localhost:{}/tp5/globo.com/www.globo.com/index.html",
    "http://localhost:{}/tp5/spiegel.de/www.spiegel.de/index.html",
    "http://localhost:{}/tp5/dailymotion.com/www.dailymotion.com/us.html",
    "http://localhost:{}/tp5/goo.ne.jp/goo.ne.jp/index.html",
    "http://localhost:{}/tp5/alipay.com/www.alipay.com/index.html",
    "http://localhost:{}/tp5/stackoverflow.com/stackoverflow.com/questions/184618/what-is-the-best-comment-in-source-code-you-have-ever-encountered.html",
    "http://localhost:{}/tp5/nicovideo.jp/www.nicovideo.jp/index.html",
    "http://localhost:{}/tp5/ezinearticles.com/ezinearticles.com/index.html@Migraine-Ocular---The-Eye-Migraines&id=4684133.html",
    "http://localhost:{}/tp5/taringa.net/www.taringa.net/index.html",
    "http://localhost:{}/tp5/tmall.com/www.tmall.com/index.html@ver=2010s.html",
    "http://localhost:{}/tp5/huffingtonpost.com/www.huffingtonpost.com/index.html",
    "http://localhost:{}/tp5/deviantart.com/www.deviantart.com/index.html",
    "http://localhost:{}/tp5/media.photobucket.com/media.photobucket.com/image/funny%20gif/findstuff22/Best%20Images/Funny/funny-gif1.jpg@o=1.html",
    "http://localhost:{}/tp5/douban.com/www.douban.com/index.html",
    "http://localhost:{}/tp5/imgur.com/imgur.com/gallery/index.html",
    "http://localhost:{}/tp5/reddit.com/www.reddit.com/index.html",
    "http://localhost:{}/tp5/digg.com/digg.com/news/story/New_logo_for_Mozilla_Firefox_browser.html",
    "http://localhost:{}/tp5/filestube.com/www.filestube.com/t/the+vampire+diaries.html",
    "http://localhost:{}/tp5/dailymail.co.uk/www.dailymail.co.uk/ushome/index.html",
    "http://localhost:{}/tp5/whois.domaintools.com/whois.domaintools.com/mozilla.com.html",
    "http://localhost:{}/tp5/indiatimes.com/www.indiatimes.com/index.html",
    "http://localhost:{}/tp5/rambler.ru/www.rambler.ru/index.html",
    "http://localhost:{}/tp5/torrentz.eu/torrentz.eu/search@q=movies.html",
    "http://localhost:{}/tp5/reuters.com/www.reuters.com/index.html",
    "http://localhost:{}/tp5/foxnews.com/www.foxnews.com/index.html",
    "http://localhost:{}/tp5/xinhuanet.com/xinhuanet.com/index.html",
    "http://localhost:{}/tp5/56.com/www.56.com/index.html",
    "http://localhost:{}/tp5/bild.de/www.bild.de/index.html",
    "http://localhost:{}/tp5/guardian.co.uk/www.guardian.co.uk/index.html",
    "http://localhost:{}/tp5/w3schools.com/www.w3schools.com/html/default.asp.html",
    "http://localhost:{}/tp5/naver.com/www.naver.com/index.html",
    "http://localhost:{}/tp5/blogfa.com/blogfa.com/index.html",
    "http://localhost:{}/tp5/terra.com.br/www.terra.com.br/portal/index.html",
    "http://localhost:{}/tp5/ucoz.ru/www.ucoz.ru/index.html",
    "http://localhost:{}/tp5/yelp.com/www.yelp.com/biz/alexanders-steakhouse-cupertino.html",
    "http://localhost:{}/tp5/wsj.com/online.wsj.com/home-page.html",
    "http://localhost:{}/tp5/noimpactman.typepad.com/noimpactman.typepad.com/index.html",
    "http://localhost:{}/tp5/myspace.com/www.myspace.com/albumart.html",
    "http://localhost:{}/tp5/google.com/www.google.com/search@q=mozilla.html",
    "http://localhost:{}/tp5/orange.fr/www.orange.fr/index.html",
    "http://localhost:{}/tp5/php.net/php.net/index.html",
    "http://localhost:{}/tp5/zol.com.cn/www.zol.com.cn/index.html",
    "http://localhost:{}/tp5/mashable.com/mashable.com/index.html",
    "http://localhost:{}/tp5/etsy.com/www.etsy.com/category/geekery/videogame.html",
    "http://localhost:{}/tp5/gmx.net/www.gmx.net/index.html",
    "http://localhost:{}/tp5/csdn.net/csdn.net/index.html",
    "http://localhost:{}/tp5/xunlei.com/xunlei.com/index.html",
    "http://localhost:{}/tp5/hatena.ne.jp/www.hatena.ne.jp/index.html",
    "http://localhost:{}/tp5/icious.com/www.delicious.com/index.html",
    "http://localhost:{}/tp5/repubblica.it/www.repubblica.it/index.html",
    "http://localhost:{}/tp5/web.de/web.de/index.html",
    "http://localhost:{}/tp5/slideshare.net/www.slideshare.net/jameswillamor/lolcats-in-popular-culture-a-historical-perspective.html",
    "http://localhost:{}/tp5/telegraph.co.uk/www.telegraph.co.uk/index.html",
    "http://localhost:{}/tp5/seesaa.net/blog.seesaa.jp/index.html",
    "http://localhost:{}/tp5/wp.pl/www.wp.pl/index.html",
    "http://localhost:{}/tp5/aljazeera.net/aljazeera.net/portal.html",
    "http://localhost:{}/tp5/w3.org/www.w3.org/standards/webdesign/htmlcss.html",
    "http://localhost:{}/tp5/homeway.com.cn/www.hexun.com/index.html",
    "http://localhost:{}/tp5/facebook.com/www.facebook.com/Google.html",
    "http://localhost:{}/tp5/youtube.com/www.youtube.com/music.html",
    "http://localhost:{}/tp5/people.com.cn/people.com.cn/index.html"
]

__all__ = ["MAX_TABS",
           "PER_TAB_PAUSE",
           "SETTLE_WAIT_TIME",
           "ITERATIONS",
           "TEST_SITES_TEMPLATES",
           "webservers",
           "process_perf_data"]
